### ISSUE TITLE
评估去 X 化的可能性

### ISSUE THREAD

**Issue by zenozeng** [zenozeng/chromemacs#2]
- http://v2ex.com/t/137252
- http://thiemonge.org/getting-started-with-uinput
- https://github.com/tuomasjjrasanen/python-uinput

**Comment by zenozeng** [comment]
@DreaminginCodeZH 有兴趣一起试试看嘛？大概项目语言会是 python

**Comment by zenozeng** [comment]
https://github.com/gvalkov/python-evdev

**Comment by zenozeng** [comment]
use python-wnck for window.

**Comment by zhanghai** [comment]
Looks great :P

Will have a look later~
